apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-scale-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-scale-poc
  template:
    metadata:
      labels:
        app: dotnet-scale-poc
    spec:
      containers:
        - name: dotnet-scale-poc
          image: dotnet-scale-poc:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"