apiVersion: v1
kind: Service
metadata:
  name: dotnet-scale-poc
  namespace: artur-guttman-dev
  labels:
    app: dotnet-scale-poc
spec:
  selector:
    app: dotnet-scale-poc
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  type: ClusterIP
