apiVersion: v1
kind: ServiceAccount
metadata:
  name: dotnet-scale-poc-sa
  namespace: artur-guttman-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dotnet-scale-poc-role
  namespace: artur-guttman-dev
rules:
  # Permisiuni pentru a citi ?i scala deployment-uri
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  # Permisiuni pentru subresource /scale
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dotnet-scale-poc-rolebinding
  namespace: artur-guttman-dev
subjects:
  - kind: ServiceAccount
    name: dotnet-scale-poc-sa
    namespace: artur-guttman-dev
roleRef:
  kind: Role
  name: dotnet-scale-poc-role
  apiGroup: rbac.authorization.k8s.io
